### ISSUE TITLE
Can't insert empty string to not nullable field

### ISSUE THREAD

**Issue by sbatykov** [mshepanski/quince_sqlite#1]
Now I can't insert empty string ("") to not nullable field.

I inspect problem and find this:
`case column_type::string:           return sqlite3_bind_text(_stmt, index, c.chars(), int(c.size()), SQLITE_TRANSIENT);`

**sqlite3_bind_text** expect pointer to char array, but then **cell** keep empty string **c.chars()** returns **nullptr** and this cause **sqlite3_bind_text** acts as **sqlite3_bind_null**.

**Comment by mshepanski** [comment]
Thanks for reporting this.
The bug was in the quince library, and would have affected postgresql users as well as sqlite users.
I have checked in a fix on the dev branch of quince. Could you please check that it does what you need. If so, then I will merge it to master.

**Comment by mshepanski** [comment]
I have merged the fix to the master branch.

**Comment by sbatykov** [comment]
Thank you. I check fix on my project, all work fine.
